### ISSUE TITLE
Setup Programmatically?

### ISSUE THREAD

**Issue by geogerar** [Sahilberi/SwiftScrollingLabel#2]
Hi,

Can you tell me how can I setup programmatically?
I try to set iy up but after I got an error.....like =====>

**ViewController.swift:53:9: Use of unresolved identifier 'toolbar_lbl'**

my code is following ======>
------------------------------------------------------------------------------------------
import UIKit

class ViewController: UIViewController
{
    @IBOutlet var main_button: UIButton!
    @IBOutlet var tool_bar: UIToolbar!
    
    class Metrites_class
    {
        static var metritis: Double = 0.0
        static var lektiko: String = ""
    }
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.

        main_button.backgroundColor = UIColor.darkGray
        main_button.layer.backgroundColor = UIColor.darkGray.cgColor
        main_button.layer.borderWidth = 2.0
        main_button.layer.borderColor = UIColor.red.cgColor
        main_button.layer.cornerRadius = 10.0
        
        let toolbar_lbl: SwiftyScrollingLabel = SwiftyScrollingLabel(frame: CGRect(x: 10, y: 2, width: self.view.frame.size.width-20, height: 40))
        
        toolbar_lbl.backgroundColor = UIColor.clear
        toolbar_lbl.labelBgColor = UIColor.clear
        toolbar_lbl.right = true
        toolbar_lbl.labelText = "Good Morning SWIFT!!!"
        toolbar_lbl.layer.backgroundColor = UIColor.clear.cgColor
        toolbar_lbl.layer.borderColor = UIColor.white.cgColor
        toolbar_lbl.layer.borderWidth = 1.0
        toolbar_lbl.layer.cornerRadius = 5.0
        
        tool_bar.addSubview(toolbar_lbl)
    }
    
    override func viewDidAppear(_ animated: Bool)
    {
        super.viewDidAppear(animated)
  
        toolbar_lbl.startAnimate()
    }
---------------------------------------------------------------------------------------------
Thanks in advance

George Gerardis

**Comment by hamentmiglani** [comment]
Hi,
  George Gerardis 

You are getting this issue because, you are creating toolbar_lbl locally in scope of method, so u can not use outside of method

To Solve this issue
Create 
let toolbar_lbl: SwiftyScrollingLabel in class like that

> class ViewController: UIViewController
> {
> @IBOutlet var main_button: UIButton!
> @IBOutlet var tool_bar: UIToolbar! 
> 
> let toolbar_lbl: SwiftyScrollingLabel!
> }

and in viewDidLoad remove let from toolbar_lbl.

Please find screenshot with update code:
![screen shot 2017-05-20 at 10 02 33 am](https://cloud.githubusercontent.com/assets/13433630/26272977/8a813686-3d43-11e7-9f26-bc73e476fdee.png)
